{% set goname = "github.com/github/hub" %}
{% set version = "2.12.3" %}

{% set name = goname.split('/')[-1] %}
{% set pkg_src = ('src/'+goname).replace("/",os.sep) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - folder: {{ pkg_src }}
    url: https://{{ goname }}/archive/v{{ version }}.tar.gz
    sha256: 197242fea670353688c541d2e4584b449f18c354a01d89bf1667ea33c0071ddc

build:
  number: 0
  script:
    - pushd {{ pkg_src }}
    - go install -v .

    # Note the semicolons
    - >-
      bash -euf -c '                                           # [ win ]
        etc_conda=$PREFIX/etc/conda;
        etc_completion=$PREFIX/etc/bash_completion.d;          # [unix]
        etc_completion=$LIBRARY_PREFIX/etc/bash_completion.d;  # [win]
        for F in activate deactivate; do
          mkdir -p $etc_conda/$F.d;
          cp -v $RECIPE_DIR/$F.sh $etc_conda/$F.d/hub.sh;
          cp -v $RECIPE_DIR/$F.ps1 $etc_conda/$F.d/hub.ps1;    # [win]
        done;
        mkdir -p $etc_completion;
        cp etc/hub.bash_completion.sh $etc_completion/hub.sh;
      '                                                        # [win]

requirements:
  build:
    - {{ compiler('go') }}
    - m2-coreutils  # [ win ]
    - m2-bash  # [win]

test:
  requires:
    - m2-grep  # [ win ]
  commands:
    - >-
      bash -euf -c "                                           # [win]
        hub version
          | grep -q '{{ name }} version {{ version }}';
        etc_conda=$PREFIX/etc/conda;
        for F in activate deactivate; do
          test -r $etc_conda/$F.d/hub.sh;
          test -f $etc_conda/$F.d/hub.ps1;                     # [win]
        done;
        test -r $PREFIX/etc/bash_completion.d/hub.sh;          # [unix]
        test -r $LIBRARY_PREFIX/etc/bash_completion.d/hub.sh;  # [win]
      "                                                        # [win]

about:
  home: https://github.com/github/hub
  license: MIT
  license_family: MIT
  license_file: src/github.com/github/hub/LICENSE
  summary: 'git + hub = github'

  description: |
    hub is a command line tool that wraps git in order to extend it with
    extra features and commands that make working with GitHub easier.
  dev_url: https://github.com/github/hub

extra:
  recipe-maintainers:
    - sodre
    - asford
