{% set name = "hub" %}
{% set version = "2.3.0-pre10" %}
{% set sha256 = "4096b95aea46f674e91ff0d83f86d876958024a02c50ffb1e3a4aac3e0536fc5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/github/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - go >=1.8
    - toolchain
    - posix  # [win]
  run:
    - git >=1.7.3

test:
  commands:
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - hub version

about:
  home: https://github.com/github/hub
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'git + hub = github'

  description: |
    hub is a command line tool that wraps git in order to extend it with
    extra features and commands that make working with GitHub easier.
  dev_url: https://github.com/github/hub

extra:
  recipe-maintainers:
    - sodre
